#!/bin/bash

set -e

action="$1" ; shift
semaphore_path="$1" ; shift

test -f "${semaphore_path}"
test -s "${semaphore_path}"

lock() {
    while ! mkdir "${semaphore_path}.lock" 2> '/dev/null' ; do
	sleep 0.01
    done
}

unlock() {
    rmdir "${semaphore_path}.lock"
}

action_p() {
    while true ; do
	lock
	count="$(cat "${semaphore_path}")"
	if [ ${count} -eq 0 ] ; then
	    unlock
	    sleep 0.5
	else
	    echo $(( count - 1 )) > "${semaphore_path}"
	    unlock
	    break
	fi
    done
}

action_v() {
    lock
    count="$(cat "${semaphore_path}")"
    echo $(( count + 1 )) > "${semaphore_path}"
    unlock
}

case "x${action}" in
    'xp') action_p ;;
    'xv') action_v ;;
    *)    exit 1 ;;
esac
