#!/bin/bash

set -e

for src in "$@" ; do
    source "${src}"
done

test "x${region}" != 'x'
test "x${instance_id}" != 'x'
test "x${egg}" != 'x'

aws ec2 terminate-instances \
  --region="${region}"\
  --instance-ids="${instance_id}" \
> '/dev/null'

rm "${egg}"
