#!/bin/bash
#
#   install-builder - install a quorum machine from official sources
#

set -e
set -x


quorum_src="${0%/*}"
quorum_source='https://github.com/Consensys/quorum.git:master'
istanbul_source='https://github.com/ConsenSys/istanbul-tools.git:master'


output="$1"          ; shift ; test "x${output}" != 'x'

for src in "$@" ; do
    source "${src}"
done

test "x${ip}" != 'x'
test "x${silk_port}" != 'x'
test "x${home_path}" != 'x'
test "x${system}" != 'x'


# Defines all commonly used directories used later in this script.
#
source "${quorum_src}/environment" "${home_path}"


# Select the system specific directory for the machine to upload files from.
#
case "${system}" in
    'apt')
	system_src="${quorum_src}/apt"
	;;
    *)
	echo "system not supported: '${system}'" >&2
	exit 1
	;;
esac


# Upload all scripts from the hatchery machine to the builder machine.
# A builder machine gets all the files in 'common' as well as the files in the
# directory named by the machine system (e.g. 'apt').
#
silk run --source --local-command "${ip}:${silk_port}" <<EOF
#!/bin/bash

set -e

if [ ! -e '${quorum_dir}' ] ; then
    mkdir '${quorum_dir}'
fi

if [ -e '${quorum_builder_dir}' ] ; then
    chmod -R 777 '${quorum_builder_dir}'
    rm -rf '${quorum_builder_dir}'
fi

mkdir '${quorum_builder_dir}'
mkdir '${quorum_builder_dir}/script'
EOF

silk send --target-directory="${quorum_builder_dir}/script" --compress \
     "${ip}:${silk_port}" "${system_src}/"* "${quorum_src}/common/"*

silk send --target-directory="${quorum_builder_dir}" --compress \
     "${ip}:${silk_port}" "${quorum_src}/toolbox"


# Perform the install on the remote machine.
# At the end of this command, the remote machine has all the executable files
# located in the regular bin directory for Quorum.
#
silk run --source --local-command -C"${quorum_builder_dir}" \
     "${ip}:${silk_port}" <<EOF
#!/bin/bash

set -e
set -x

# Install all packages and tools necessary for the download and compilation of
# Quorum from sources.
#
'${quorum_builder_dir}/script/install'

# Create the node binary directory if it does not exist yet.
#
if [ ! -e '${quorum_bin_dir}' ] ; then
    mkdir '${quorum_bin_dir}'
fi

# Build Quorum and related official tools from sources.
# Install important tools in the node binary directory.
#
'${quorum_builder_dir}/script/build' '${quorum_bin_dir}'  \\
                                     '${quorum_source}'   \\
                                     '${istanbul_source}'

# Build the Quorum toolbox for this module.
# Install the toolbox in the node binary directory.
#
go build -o '${quorum_bin_dir}/toolbox' '${quorum_dir}/builder/toolbox/'*'.go'
EOF


cat "$@" > "${output}"
