#!/bin/bash
#
#   environment - defines commonly used paths and variables on hatchery machine
#


# Top directory to put files related to Quorum on remote machines.
#
quorum_dir="quorum"


# Top directory to work in for the builder machines.
#
quorum_builder_dir="${quorum_dir}/builder"


# Top directory to put executables to be used by a Quorum node.
#
quorum_bin_dir="${quorum_dir}/bin"


# Top directory to put files during a Quorum deployment.
#
quorum_run_dir="${quorum_dir}/run"
