#!/bin/bash
#
#   prepare - Prepare all configuration files
#
#   Syntax: ./prepare <output> <input> <arch-asset>
#
#   Prepare a given <output> asset used by the system during a test.
#   Use the machine described in the <input> shell configuration file to
#   prepare the asset.
#   If the <input> machines needs assets to work (e.g. binaries), find these
#   required assets in the <arch-asset> directory.
#   Deduce the type and properties of the <output> asset based on its name.
#


set -e


output="$1"     ; shift ; test "x${output}" != 'x'
input="$1"      ; shift ; test "x${input}" != 'x'
arch_asset="$1" ; shift ; test "x${arch_asset}" != 'x'

source "${input}"

test "x${ip}" != 'x'          # has a known IP address
test "x${silk_port}" != 'x'   # has Silk running and listening on a known port
test "x${system}" != 'x'      # has a known package manager

if [ -e "${output}" ] ; then
    rm -rf "${output}"
fi


# System specific prepare part ------------------------------------------------

# The only asset we can build for Quorum is a "network" (e.g. static-nodes,
# genesis files and nodekeys).
#
# Deduce the size of the network to build from the name: 'base.' <size>.
#
size="${output##*/base.}"

echo "${size}" | grep -Pq '^\d+$'
test ${size} -gt 0


quorum_src="${0%/*}"

source "${quorum_src}/environment"


test -f "${arch_asset}/istanbul"
test -f "${arch_asset}/toolbox"


# Upload all binaries from the hatchery machine to the prepare machine.
#
silk run --source --local-command "${ip}:${silk_port}" <<EOF
#!/bin/bash

mkdir '${quorum_dir}' 2> '/dev/null'
mkdir '${quorum_bin_dir}' 2> '/dev/null'

set -e

test -d '${quorum_bin_dir}'
EOF

silk send --target-directory="${quorum_bin_dir}" "${ip}:${silk_port}" \
     "${arch_asset}/"*


workdir="$(mktemp -d --suffix='.d' "${0##*/}.XXXXXX")"
trap "rm -rf '${workdir}'" EXIT


# Run the toolbox on the prepare machine to create the asset and download it
# directly in a temporary directory.
#
mkdir "${workdir}/output"
(
    cd "${workdir}/output"

    silk run --source --local-command \
	 "${ip}:${silk_port}" <<EOF | tar -ixzpf -
#!/bin/bash

set -e

export PATH="\${PWD}/${quorum_bin_dir}:\${PATH}"

tempdir="\$(mktemp -d --suffix='.tmp' 'asset.${size}.XXXXXX')"
trap "rm -rf '\${tempdir}'" EXIT

toolbox new -s ${size} "\${tempdir}/asset"

(
    cd "\${tempdir}/asset"
    tar -czf - *
)
EOF
)

mv "${workdir}/output" "${output}"
